name: Java CI with Maven

on:
    push:
        branches:
        - master
        - "v[0-9]+.[0-9]+.x"

    pull_request:
        branches:
        - master
        - "v[0-9]+.[0-9]+.x"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-latest]
                java: [11, 12, 15]
                arch: [x64] # when ARM will be present add aarch64
            fail-fast: false
            max-parallel: 4
        name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

        steps:
            - name: Checkout Source
              uses: actions/checkout@v2

            - name: Install Libraries
              run: sudo apt-get install libssl1.0.0

            - name: Cache maven repository
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.m2/repository
                  key: ${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}
                      ${{ matrix.arch }}-${{ runner.os }}-maven

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
                  architecture: ${{ matrix.arch }}
            - name: Test with Maven
              run: mvn verify -B --file pom.xml

